look_for(ces19phone, "ethnic")
ces19phone$q66a_17_
#Take ces19phone
ces19phone %>% 
  #mutate to make vismin1 when conditions apply
  #I am calling this vismin1 so that we can merge this variable with the vismin_text that comes below.
  mutate(vismin1=case_when(
  #These are all different dichotomous variables that the R selected if that ethnicity applied to them. If they selected a visible minority ethnicty, vismin takes 1; if they selected a non-vismin ethcnity vismin takes 0
    q66a_1==1~0,
        q66a_2==1~0,
        q66a_3==1~0,
        q66a_4==1~0,
        q66a_5==1~0,
        q66a_6==1~0,
        q66a_7==1~1,
        q66a_8==1~0,
        q66a_9==1~0,
        q66a_10==1~0,
        q66a_11==1~1,
        q66a_12==1~0,
        q66a_13==1~0,
        q66a_14==1~0,
        q66a_15==1~1,
        q66a_16==1~0
  ))->ces19phone

#Turn the remainder into all lower text
ces19phone$vismin_text<-str_to_lower(ces19phone$q66a_17_)


ces19phone %>% 
  mutate(vismin2=case_when(
    str_detect(vismin_text, "akan")~1, 
    str_detect(vismin_text, "white")~0,
        str_detect(vismin_text, "caucasian")~0,
  str_detect(vismin_text, "syrian")~1,
    str_detect(vismin_text, "african")~1,
    str_detect(vismin_text, "africain")~1,
      str_detect(vismin_text, "acadien")~1,
        str_detect(vismin_text, "afro")~1,
        str_detect(vismin_text, "acadian")~1,
          str_detect(vismin_text, "afghan")~1,
            str_detect(vismin_text, "afrique")~1,
            str_detect(vismin_text, "afghan")~1,
            str_detect(vismin_text, "american")~0,
            str_detect(vismin_text, "ameridien")~1,
              str_detect(vismin_text, "algérienne")~1,
              str_detect(vismin_text, "algerien")~1,
              str_detect(vismin_text, "anglo")~0,
              str_detect(vismin_text, "arab")~1,
              str_detect(vismin_text, "angliphone")~0,
              str_detect(vismin_text, "arib")~1,
              str_detect(vismin_text, "ameridien")~1,
              str_detect(vismin_text, "arican")~1,
              str_detect(vismin_text, "africian")~1,
              str_detect(vismin_text, "ahmadiyyat")~1,
                str_detect(vismin_text, "argentin")~1,
                str_detect(vismin_text, "amérindien")~1,
                str_detect(vismin_text, "ahmadiyyat")~1,
                str_detect(vismin_text, "asia")~1,
                str_detect(vismin_text, "aucun")~0,
                str_detect(vismin_text, "australian")~1,
                str_detect(vismin_text, "austrian")~1,
                str_detect(vismin_text, "austro")~1,
                str_detect(vismin_text, "belgi")~1,
                str_detect(vismin_text, "bangla")~1,
                str_detect(vismin_text, "beligi")~1,
                str_detect(vismin_text, "armenian")~1,
                str_detect(vismin_text, "antillais")~1,
                str_detect(vismin_text, "belge")~1,
                str_detect(vismin_text, "berbèr")~1,
                str_detect(vismin_text, "blackfoot")~1,
                str_detect(vismin_text, "black")~1,
              str_detect(vismin_text, "blanc")~0,
                str_detect(vismin_text, "balnc")~0,
                str_detect(vismin_text, "british")~0,
                str_detect(vismin_text, "breton")~1,
                str_detect(vismin_text, "bosnian")~1,
                str_detect(vismin_text, "bulgarian")~0,
                str_detect(vismin_text, "cameroun")~1,
                str_detect(vismin_text, "brézilien")~1,
                str_detect(vismin_text, "swiss")~0,
                str_detect(vismin_text, "ukrainian")~0,
                str_detect(vismin_text, "canadien")~0,
                str_detect(vismin_text, "caraibéenne")~1,
                  str_detect(vismin_text, "carrabian")~1,
                    str_detect(vismin_text, "carribean")~1,
                      str_detect(vismin_text, "carribean")~1,
                      str_detect(vismin_text, "carriean")~1,
                      str_detect(vismin_text, "cascausain")~0,
  str_detect(vismin_text, "cascausian")~0,
  str_detect(vismin_text, "cauasion")~0, 
  str_detect(vismin_text, "caucasien")~0, 
  str_detect(vismin_text, "caucasion")~0,
  str_detect(vismin_text, "caucausian")~0,
  str_detect(vismin_text, "caucausian")~0, 
  str_detect(vismin_text, "causasien")~0, 
  str_detect(vismin_text, "causasion")~0, 
  str_detect(vismin_text, "chile")~1, 
  str_detect(vismin_text, "chrilancan")~1, 
  str_detect(vismin_text, "cocasien")~0, 
  str_detect(vismin_text, "cocassien")~0,
    str_detect(vismin_text, "congolais")~1,
    str_detect(vismin_text, "coréen")~1,
    str_detect(vismin_text, "croatian")~0,
    str_detect(vismin_text, "cuban")~1,
    str_detect(vismin_text, "czech")~0,
    str_detect(vismin_text, "danish")~0,
    str_detect(vismin_text, "denmark")~0,
  str_detect(vismin_text, "dominicain")~1, 
  str_detect(vismin_text, "dominican")~1, 
    str_detect(vismin_text, "dutch")~0,
    str_detect(vismin_text, "east european")~0,
    str_detect(vismin_text, "east indian")~0,
    str_detect(vismin_text, "eastern european")~0,
  str_detect(vismin_text, "ecossais")~0,
    str_detect(vismin_text, "francais")~0,
    str_detect(vismin_text, "egyptian")~0,
      str_detect(vismin_text, "egytian")~0,
      str_detect(vismin_text, "endo canadian")~0,
      str_detect(vismin_text, "english")~0,
      str_detect(vismin_text, "englo")~0,
      str_detect(vismin_text, "eukranian")~0,
      str_detect(vismin_text, "europe")~0,
  str_detect(vismin_text, "européens")~0, 
  str_detect(vismin_text, "dont have")~0, 
  str_detect(vismin_text, "eurpean")~0, 
  str_detect(vismin_text, "do not identify")~0, 
  str_detect(vismin_text, "fijian")~1, 
  str_detect(vismin_text, "filipino")~1, 
  str_detect(vismin_text, "finish")~0,
  str_detect(vismin_text, "findland")~0, 
str_detect(vismin_text, "finnish")~0,
str_detect(vismin_text, "swedish")~0, 
str_detect(vismin_text, "norwegian")~0,
str_detect(vismin_text, "finland")~0,
str_detect(vismin_text, "flippino")~1,
str_detect(vismin_text, "franco manitobain")~0, 
str_detect(vismin_text, "franco ontarien")~0,
str_detect(vismin_text, "francophone")~0,
str_detect(vismin_text, "francophones")~0, 
str_detect(vismin_text, "french")~0,
str_detect(vismin_text, "german")~0,
str_detect(vismin_text, "culturally dominant")~0,
str_detect(vismin_text, "text")~1, 
str_detect(vismin_text, "greek")~0,
str_detect(vismin_text, "greque")~0, 
str_detect(vismin_text, "greece")~0, 
str_detect(vismin_text, "gujarati")~1, 
str_detect(vismin_text, "haiti")~1, 
str_detect(vismin_text, "haitien")~1, 
str_detect(vismin_text, "haitian")~1, 
str_detect(vismin_text, "haitienne")~1, 
str_detect(vismin_text, "han chinese")~1, 
str_detect(vismin_text, "slavic")~0, 
str_detect(vismin_text, "haiti")~1, 
str_detect(vismin_text, "heinz")~0, 
str_detect(vismin_text, "hindu")~1, 
str_detect(vismin_text, "hispanic")~1, 
str_detect(vismin_text, "hipanophone")~1,
str_detect(vismin_text, "hispanophone")~1, 
str_detect(vismin_text, "human")~0, 
str_detect(vismin_text, "hongrois")~0, 
str_detect(vismin_text, "hungarian")~0, 
str_detect(vismin_text, "hungary")~0, 
str_detect(vismin_text, "hungry")~0, 
str_detect(vismin_text, "ibo")~1, 
str_detect(vismin_text, "icelandic")~0, 
str_detect(vismin_text, "iclandic")~0, 
str_detect(vismin_text, "icelantic")~0,
str_detect(vismin_text, "arménéen")~0,
str_detect(vismin_text, "arménien")~0,
str_detect(vismin_text, "indo ")~1,
str_detect(vismin_text, "irish")~0,
str_detect(vismin_text, "innue")~1, 
str_detect(vismin_text, "israel")~0,
str_detect(vismin_text, "iranian")~1, 
str_detect(vismin_text, "jamaican")~1, 
str_detect(vismin_text, "jamacian")~1, 
str_detect(vismin_text, "jamaica")~1,
str_detect(vismin_text, "jamacia")~1, 
str_detect(vismin_text, "japanese")~1,
str_detect(vismin_text, "jamican")~1, 
str_detect(vismin_text, "jewish orthisdox")~1, 
str_detect(vismin_text, "jewish")~0,
str_detect(vismin_text, "judaism")~0, 
str_detect(vismin_text, "kurdish")~1,
str_detect(vismin_text, "korean")~1, 
str_detect(vismin_text, "laos")~1, 
str_detect(vismin_text, "latine")~1, 
str_detect(vismin_text, "latin")~1, 
str_detect(vismin_text, "latino")~1, 
str_detect(vismin_text, "latins")~1, 
str_detect(vismin_text, "latvian")~0, 
str_detect(vismin_text, "lithuanian")~0,
str_detect(vismin_text, "liban")~1,
str_detect(vismin_text, "libanaise")~1,
str_detect(vismin_text, "lebanese")~1, 
str_detect(vismin_text, "lithuanian")~0, 
str_detect(vismin_text, "maltese")~0, 
str_detect(vismin_text, "lithuwaning")~0,
str_detect(vismin_text, "maritime")~0,
str_detect(vismin_text, "maori")~1, 
str_detect(vismin_text, "mediterranean")~0,
str_detect(vismin_text, "moroccan")~1, 
str_detect(vismin_text, "marocaine")~1, 
str_detect(vismin_text, "mennonite")~0,
str_detect(vismin_text, "mennanite")~0,
str_detect(vismin_text, "mennoonite")~0, 
str_detect(vismin_text, "menon")~0,
str_detect(vismin_text, "mexiq")~1,
str_detect(vismin_text, "mexic")~1,
str_detect(vismin_text, "middle east")~1, 
str_detect(vismin_text, "midde east")~1,
str_detect(vismin_text, "middleeast")~1,
str_detect(vismin_text, "mikmaq")~1, 
str_detect(vismin_text, "moldav")~0,
str_detect(vismin_text, "morroc")~1, 
str_detect(vismin_text, "mix") ~ 0,
str_detect(vismin_text, "multiple")~0, 
str_detect(vismin_text, "muslim")~1, 
str_detect(vismin_text, "nepali")~1, 
str_detect(vismin_text, "newfound")~0, 
str_detect(vismin_text, "netherland")~0,
str_detect(vismin_text, "normand")~0, 
str_detect(vismin_text, "norweigen")~0, 
str_detect(vismin_text, "norweigian")~0,
str_detect(vismin_text, "old people")~0,
str_detect(vismin_text, "pakistan")~1, 
str_detect(vismin_text, "papouasie")~1, 
str_detect(vismin_text, "none")~0, 
str_detect(vismin_text, "paraguay")~1, 
str_detect(vismin_text, "partially native")~0, 
str_detect(vismin_text, "part native")~0, 
str_detect(vismin_text, "pashton")~1,
str_detect(vismin_text, "pays bas")~0, 
str_detect(vismin_text, "phillipin")~1, 
str_detect(vismin_text, "phillippin")~1, 
 str_detect(vismin_text, "philipino")~1, 
str_detect(vismin_text, "philippines")~1, 
str_detect(vismin_text, "philippino")~1, 
str_detect(vismin_text, "portug")~0, 
str_detect(vismin_text, "persian")~1, 
str_detect(vismin_text, "poto")~0,
str_detect(vismin_text, "punjabi")~1,
str_detect(vismin_text, "romanian")~0,
str_detect(vismin_text, "roumain")~0, 
str_detect(vismin_text, "rushion")~0, 
str_detect(vismin_text, "russia")~0, 
str_detect(vismin_text, "saxophon")~0,
str_detect(vismin_text, "scandinavian")~0,
str_detect(vismin_text, "scandinavion")~0, 
str_detect(vismin_text, "scandanavian")~0, 
str_detect(vismin_text, "scandanavin")~0, 
str_detect(vismin_text, "settler")~0, 
str_detect(vismin_text, "sikh")~1, 
str_detect(vismin_text, "serbia")~0, 
str_detect(vismin_text, "slovak")~0, 
str_detect(vismin_text, "slovan")~0,
str_detect(vismin_text, "somali")~0, 
str_detect(vismin_text, "spanish")~0, 
str_detect(vismin_text, "sri lankan")~1, 
str_detect(vismin_text, "sudan")~1, 
str_detect(vismin_text, "suisse")~0,
str_detect(vismin_text, "surbian")~0,
str_detect(vismin_text, "sweddish")~0, 
str_detect(vismin_text, "sweden")~0, 
str_detect(vismin_text, "taiwanese")~1,
str_detect(vismin_text, "tamil")~1,
str_detect(vismin_text, "thai")~1, 
str_detect(vismin_text, "tigvrina")~1, 
str_detect(vismin_text, "tunisien")~1, 
str_detect(vismin_text, "turkish")~1,
str_detect(vismin_text, "ukraine")~0,
str_detect(vismin_text, "united empire loyalist")~0,
str_detect(vismin_text, "united states")~0,
str_detect(vismin_text, "united kingdom")~0,
str_detect(vismin_text, "urdu")~1,
str_detect(vismin_text, "vietnamese")~1, 
str_detect(vismin_text, "vietnam")~1,
str_detect(vismin_text, "viking")~0, 
str_detect(vismin_text, "wasp")~0,
str_detect(vismin_text, "welch")~0, 
str_detect(vismin_text, "welsh")~0, 
str_detect(vismin_text, "west indian")~1, 
str_detect(vismin_text, "ango saxon")~0, 
str_detect(vismin_text, "wap")~0,
str_detect(vismin_text, "wosp")~0, 
    ))->ces19phone
#Running the code from the top of the script to line 268 (View) Will run the whole mutate case_when and then bring up a View screen that shows the remaining text answers to be coded. It helps to make things go really quickly 
ces19phone %>% 
  filter(is.na(vismin2)) %>% 
    distinct(vismin_text, vismin2) %>% 
group_by(vismin_text) %>% 
  summarize(n=n()) 
#View() #Note I am turning off the View() command so that when the Recode script runs, it doesn't pop up a viewer. If you have to get into this in detail, just ad d a pipe %>% after summarize(n-n()) and feed it to View(). 

#combine the responses from vismin1 (dichotomous yes/no variables) and vismin2 (text responses )into vismin
ces19phone %>% 
  mutate(vismin=case_when(
    vismin1==1~1,
    vismin2==1~1,
    vismin1==0~0,
    vismin2==0~0
  ))->ces19phone

#Check the percentages of visible minorities in the sample
prop.table(table(ces19phone$vismin))
#Note white people are overrepresented in the sample. 
